name: SonarCloud Analysis

on:
  push:
    branches:
      - mejoras-calidad
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Deshabilitar clones superficiales para un mejor análisis
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-scan-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
